checksum:
  name_template: "{{ .ProjectName }}_sha256checksums.txt"
  algorithm: sha256
env:
  - CGO_ENABLED=0
builds:
  - id: build-windows-386
    goos:
      - windows
    goarch:
      - "386"
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
  - id: build-windows-amd64
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
  - id: build-linux-386
    goos:
      - linux
    goarch:
      - "386"
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
  - id: build-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
  - id: build-linux-armv7
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
  - id: build-linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
  - id: build-darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
  - id: build-darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
