version: 2
checksum:
  name_template: "{{ .ProjectName }}_sha256checksums.txt"
  algorithm: sha256
builds:
  - binary: payload-dumper-go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm
      - arm64
      - "386"
      - amd64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -w -s -buildid=
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
release:
  draft: true
