name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install git golang

      - uses: actions/checkout@v2

      - name: Add $GITHUB_WORKSPACE to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
