name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v5.1.0
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
